/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contacts;

import Contact.Contact;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author alex
 */
public class Contacts extends javax.swing.JFrame {

    /**
     * Creates new form Contacts
     */
    public Contacts() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/phonebook.png")).getImage());
        this.setTitle("კონტაქტები");
    }
    Edit_contacts ec=new Edit_contacts();
public Connection getconnection() {
Connection con=null;
try{
Class.forName("com.mysql.jdbc.Driver");
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/contacts", "root", "pass");
}
catch(Exception e){
e.printStackTrace();
}
return con;
}


public ArrayList<Contact> contacts(String search){
ArrayList<Contact> list=new ArrayList<Contact>();
    PreparedStatement ps;
    ResultSet rs;
    try{
    Connection con=getconnection();
    String query="select * from contact where concat(idcontact, Name, Phone) like '%"+search+"%';";
    ps=con.prepareStatement(query);
    rs=ps.executeQuery();
    
    
    Contact cont;
    while(rs.next()){
    cont=new Contact(
            rs.getInt("idcontact"),
            rs.getString("Name"), 
            rs.getInt("Phone"));
    list.add(cont);
    }
    }
    
    catch(Exception e){
    e.printStackTrace();
    }

return list;
}
public void findcontacts(){
ArrayList<Contact> list=contacts(txt_search.getText());
DefaultTableModel model=new DefaultTableModel();
model.setColumnIdentifiers(new Object[]{"id", "სახელი","მობილური"});
Object []row=new Object[4];
    for (int i = 0; i < list.size(); i++) {
        row[0]=list.get(i).getID();
        row[1]=list.get(i).getName();
        row[2]=list.get(i).getPhone();
        model.addRow(row);
    }
    jtbl_contacts.setModel(model);
}



public ArrayList<Contact> contacts(){
ArrayList<Contact> list=new ArrayList<Contact>();
    PreparedStatement ps;
    ResultSet rs;
    try{
    Connection con=getconnection();
    String query="select * from contact";
    ps=con.prepareStatement(query);
    rs=ps.executeQuery();
    
    
    Contact cont;
    while(rs.next()){
    cont=new Contact(
            rs.getInt("idcontact"),
            rs.getString("Name"), 
            rs.getInt("Phone"));
    list.add(cont);
    }
    }
    
    catch(Exception e){
    e.printStackTrace();
    }

return list;
}
public void showcontacts(){
ArrayList<Contact> list=contacts();
DefaultTableModel model=new DefaultTableModel();
model.setColumnIdentifiers(new Object[]{"id", "სახელი","მობილური"});
Object []row=new Object[4];
    for (int i = 0; i < list.size(); i++) {
        row[0]=list.get(i).getID();
        row[1]=list.get(i).getName();
        row[2]=list.get(i).getPhone();
        model.addRow(row);
    }
    jtbl_contacts.setModel(model);

}

public void sqlquery(String query, String message){
Connection con=getconnection();
Statement ps;
try{
ps=con.createStatement();
if((ps.executeUpdate(query)==1)){
    JOptionPane.showMessageDialog(null,"წარმატებით "+message);}
else {
    JOptionPane.showMessageDialog(null,"წარუმატებლად "+message);}
}
catch(Exception e){
e.printStackTrace();
}

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_search = new javax.swing.JTextField();
        jbt_search = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_Phone = new javax.swing.JTextField();
        jbt_insert = new javax.swing.JButton();
        jbt_view = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_contacts = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        txt_search.setToolTipText("გთხოვთ შეიყვანეთ მოსაძებნი სახელი");
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        jbt_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        jbt_search.setToolTipText("ძებნა");
        jbt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_searchActionPerformed(evt);
            }
        });

        jbt_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
        jbt_insert.setToolTipText("კონტაქტის დამატება");
        jbt_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_insertActionPerformed(evt);
            }
        });

        jbt_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View.png"))); // NOI18N
        jbt_view.setToolTipText("კონტაქტების ნახვა");
        jbt_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_viewActionPerformed(evt);
            }
        });

        jtbl_contacts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone"
            }
        ));
        jtbl_contacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_contactsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_contacts);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setText("სახელი:");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setText("მობილური:");

        jMenu1.setText("ფაილი");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jMenuItem1.setText("გამოსვლა");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbt_insert)
                                    .addComponent(jbt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbt_view)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_search))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbt_insert))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt_view)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jbt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_searchActionPerformed
        findcontacts();
    }//GEN-LAST:event_jbt_searchActionPerformed

    private void jbt_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_viewActionPerformed
        showcontacts();
    }//GEN-LAST:event_jbt_viewActionPerformed

    private void jtbl_contactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_contactsMouseClicked
        int index=jtbl_contacts.getSelectedRow();
        TableModel model=jtbl_contacts.getModel();
        String id= model.getValueAt(index, 0).toString();
        String name=  model.getValueAt(index, 1).toString();
        String phone= model.getValueAt(index, 2).toString();
        
        ec.setVisible(true);
        ec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ec.txt_editid.setText(id);
        ec.txt_editname.setText(name);
        ec.txt_editphone.setText(phone);
    }//GEN-LAST:event_jtbl_contactsMouseClicked

    private void jbt_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_insertActionPerformed
        String query="insert into contact(Name, Phone) values('"+txt_name.getText()+"', "+txt_Phone.getText()+")";
        sqlquery(query, "ჩაისვა");
    }//GEN-LAST:event_jbt_insertActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_insert;
    private javax.swing.JButton jbt_search;
    private javax.swing.JButton jbt_view;
    private javax.swing.JTable jtbl_contacts;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
